### ISSUE TITLE
Problems with new revisions (history & compare view)

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1028]
Newly created revisions are not found? (imho should work, but better test it again.)

**Comment by elbotho** [comment]
Steps: I edit an article (e.g. 1565) and save a new revision (not accepted). 
I see it in the legacy overview no problem.

Bug 1:
In the frontend overview it's way at the bottom (should be on the top). This is an [API bug](https://github.com/serlo/api.serlo.org/issues/369), since the IDs should come ordered.

Bug 2:
The Preview of the revision can't be opened in the frontend. With the new redirect I get stuck in a redirect loop.
For today [this link works](https://de.serlo-staging.dev/mathe/210014/sinus-kosinus-und-tangens-neu) to test.

**Comment by elbotho** [comment]
The difference between an old revision and the newly created seems to be the form the alias takes:
- new: `/mathe/210014/sinus-kosinus-und-tangens-neu`
- old: `/entity/repository/compare/1565/121199`

([api issue](https://github.com/serlo/api.serlo.org/issues/370))

**Comment by elbotho** [comment]
Both seem to be fixed! 🎉
