### ISSUE TITLE
Show license notice

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#108]
![grafik](https://user-images.githubusercontent.com/13507950/79742176-b9498d80-8302-11ea-930a-76a345b5b4b6.png)

It's probably not necessary to show the notice on every entity.

I would prefer to add a license notice cc-by-4.0 to the whole page and only show additional notices if the content is not cc-by-4.0. Any opinions?

**Comment by inyono** [comment]
Please do the same as on Serlo.org so that users that care about the license find them in the same place. If we want to change that, we need to discuss that in detail and also validate legal requirements etc., so I wouldn’t touch that right now.

You already get all needed license information via the API for entities

**Comment by Entkenntnis** [comment]
@yolo-bird are you working on this currently?

**Comment by yolo-bird** [comment]
Not exactly on this. My scope is to reduce the number of licences that are more closed than our standard licence. 

I do not know the legal requirements, so I can't help you there. But on the other hand you can have a look how we handle licences for Aufgabenangaben right now. There the licence is hidden in the menu. 
![Screenshot_2020-04-20 Aufgaben zu Kreisen und Kreisteilen](https://user-images.githubusercontent.com/46370375/79757296-31707d00-831c-11ea-8aed-4aa976bb1fb3.png)
