### ISSUE TITLE
Review view: No comparison available for current revision

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1173]
For the current revision that is live there is no comparision (diff or plain content view) available. 
See: https://www.loom.com/share/d3742236c1e0449ab900af9254d3d837

Examples for content: 
https://de.serlo-staging.dev/entity/repository/compare/52035/99983
https://de.serlo-staging.dev/entity/repository/compare/54751/192668

**Comment by elbotho** [comment]
@yolo-bird this is the same issue that is discussed [here](https://serlo.slack.com/archives/C0BMSC431/p1625682255005500) 
 and should be fixed [here](https://github.com/serlo/frontend/pull/1172) right?

**Comment by ghost** [comment]
Ah yes, I think it is the same. 

But is the reviewer view for checked out content the same as for non checked out content? (except the accept and not accept button). Like if my examples above were not already checked, I should have the comparisons that I was missing, right?

**Comment by elbotho** [comment]
we always compare to the currently accepted revision now. 
so that's why the view is different. 

Examples for article:
- [History](https://frontend-git-small-revision-improvement-serlo.vercel.app/entity/repository/history/1555)
- [Old, not accepted revision](https://frontend-git-small-revision-improvement-serlo.vercel.app/entity/repository/compare/1555/98396)
- [Currently accepted revision](https://frontend-git-small-revision-improvement-serlo.vercel.app/entity/repository/compare/1555/150196)
- [New, not accepted revision](https://frontend-git-small-revision-improvement-serlo.vercel.app/entity/repository/compare/1555/219411)

**Comment by ghost** [comment]
Thanks for the clarification. Then the new fix will solve this.
