### ISSUE TITLE
/entity/unrevised: Filtering options for reviewers

### ISSUE THREAD

**Issue by ghost** [serlo/frontend#1194]
![signal-2021-07-22-162954](https://user-images.githubusercontent.com/46370375/126656792-85d22ddf-7fab-41fe-b759-aad1af96f2db.jpeg)

We would like to have to filter options:

- for type of edit (this is where we take the information from the checkout field)
- for subjects

Default filter is all for each filter options. That is in the beginning you have a overview of all subjects with the first three unrevised entities. If you want to see more there is a button "weitere laden". If you push it (e.g. the one for math) you come to the filtered view for math. 

Filtering behaviour: 
- If you enable one filter (e.g. one subject) you only see the the unrevised revisions for the set filter
- the type of edit filters are combinable (logis is "or" -> e.g. show me all edits that are "new" and "with content change"

The number of unrevised edits that apply to a certain filter can be seen in brackets (see image).
Filtering options are only visible if there is at least one unrevised entity that applies to this filter (e.g. if there is nothing for the subject chemistry, the chemistry button is not visible)

**Comment by ghost** [comment]
ping @kathongi

**Comment by kulla** [comment]
Am I right that one can click on "Neu erstellt" and "Mathematik" at the same time?

**Comment by kathongi** [comment]
> Am I right that one can click on "Neu erstellt" and "Mathematik" at the same time?

Yes.

**Comment by kulla** [comment]
Here is my idea for how the API interface shall be:

### Hypothesis: Unrevised revisions for one entity shall be grouped:

In `/entity/unrevised` unrevised revisions for one entity are grouped together: 
![2021-08-04-150048_917x208_scrot](https://user-images.githubusercontent.com/1327215/128185556-b8886aeb-5d6a-4ac3-8dbe-621a84d464dd.png)

I guess in the new design this shall also be case. (I think the UI can be made better though since a reviewer need to know to click on the most recent unrevised revision in order to review all changes -> somehow this should be easier to archieve). Thus, I think instead of a list of unrevised revision we should model the page around a collection of unrevised revisions for an entity. This I call `UnrevisedEdit`:

```graphql
type UnrevisedEdit {
  entity: AbstractEntity!
  # The following is a list since we do not want to have pagination here
  unrevisedRevisions: [AbstractEntityRevision!]!
  newestUnrevisedRevision: AbstractEntityRevision!
}
```

It's similar to a pull request in Github, but here for an entity instead of an repository. It's a proposed change of an entity `entity` with the list of revisions  `unrevisedRevisions` and whereby `newestUnrevisedRevision` is the most current of them (e.g `newestUnrevisedRevision =unrevisedRevisions[0]`)

### Grouping

The unrevised edits are displayed in lists grouped by subjects:

```graphql
type UnrevisedEditGroup {
  subject: Subject!
  unrevisedEdits: UnrevisedEditConnection!
}

type UnrevisedEditConnection {
  nodes: [UnrevisedEdit!]!
  totalCount: Number!
  edges: ...
  pageInfo: ...
}

type Subject {
  id: String!
  taxonomy: TermTaxonomy!
  name: String # necessary?!
}
```
### Filters

There are the following main filters:

```graphql
type UnrevisedEditFilter {
  # one of the unrevised revisions is work in progress
  wip: Boolean
  # one of the unrevised revisions is the first one                  
  newlyCreated: Boolean
  # one of the unrevised revisions is a typo fix or design change
  typoOrDesign: Boolean
  # one of the unrevised revisions add new content
  newContent: Boolean
}
```

Values can be `null` which means the filter is not set (has no effect).

#### Problem

The above filter make only sense for one unrevised revision. However there might be many unrevised revisions for one entity. Take the following situation for the entity `Circle`:

| Title  | Author | Change        |
|--------|--------|---------------|
| Circle | Alice  | typo          |
|        | Alice  | wip           |
|        | Alice  | newly created |

When the filter `typo` is active, which of the unrevised Revisions shall be seen? Shall the whole group of unrevised revisions be visible or not? Do do we define for each list of unrevised revisions for one entity whether a certain filter is defined for it or not?

### Loading the main view

Given a certain default configuration of main filters like

```json
{
  "wip": false,
  "newlyCreated": null,
  "typoOrDesign": null,
  "newContent": null
}
```

The groups of unrevised edits can be fetched:

```graphql
extend type Query {
  entity: EntityQuery!
}

type EntityQuery {
  unrevisedEdits(filter: UnrevisedEditFilter!): UnrevisedEditsResult
}

type UnrevisedEditsResult {
  counts: UnrevisedEditCounts!
  # No pagination wanted here -> we return a list
  unrevisedEditGroups: [UnrevsiedEditGroup!]!
}

type UnrevisedEditCounts {
  all: Number!
  wip: Number!
  newlyCreated: Number!
  typoOrDesign: Number!
  newContent: Number!
}
```
`UnrevisedEditCounts` is to show numbers of unrevised edits for each of the main filters and the total number of unrevised edits. 

Note that  `[UnrevsiedEditGroup!]!` is enough to render the list of subjects and to implement a client side filter for all subjects to be shown.

### Loading more unrevised edits per subject

Since a "load more" button is requested for each subject group of unrevised edits there is an extra endpoint for this:

```graphql
extend type EntityQuery {
  unrevisedEditGroup(
    subjectId: String!,
    filter: UnrevisedEditFilter!,
    first: Number,
    after: String!
  ): UnrevisedEditConnection!
}
```

Since each of the subject groups `UnrevisedEditGroup` has via `unrevisedEdits` a connection with a `PageInfo` there is the info with `hasNextPage` and `endCursor` to render the "load more" button properly.

### Open Questions (ping @kathongi )

- [ x] Is it correct that the filter "created by new author" was forgotten? -> is not necessary
- [ ] Is it correct that unrevised revisions shall be always grouped for one entity and displayed in such a group?
  - [ ] When unrevsied revisions shall be grouped: What does it mean for the sorting of one table (see https://github.com/serlo/frontend/issues/1195#issuecomment-892649969 )
  - [ ] How shall such a group be rendered? Is there a better implementation than a group inside a table?
- [ ] Main filters are defined for one revision, however a change of an entity my consist of many unrevised revision. How shall the filters be defined for such a list of changes?
- [ ] What is the definition of the numbers? See https://github.com/serlo/frontend/issues/1194#issuecomment-892690252

**Comment by kulla** [comment]
> The number of unrevised edits that apply to a certain filter can be seen in brackets (see image).

@kathongi Shall this be the total number of unrevised edits / revisions for this filter or shall it change regarding other filters which are set? Two examples:

* When the filter "newly created" is active, shall the filter "mathematics" show the total number or the number of newly created unrevised revisions?
* When the filter "mathematics" is active, shall filter "newly created" show the total number of newly created entities or only those in mathematics?

**Comment by kathongi** [comment]
(@yolo-bird already discussed the open questions. The grouping stays important even if you filtered because of revisions before)

**Comment by Entkenntnis** [comment]
Thank you all for the input on this topic. To keep all backlog ideas in one place,  I have moved this topic into the [backlog](https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#) and linked it.
