### ISSUE TITLE
test all revision types

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1343]
test all revision types and investigate if all data is fetched

**Comment by elbotho** [comment]
To make it really save we should:
1. query all fields the api offers for a uuid (or check the db directly)
2. open the uuid in the edtr and add a fixed string to the title/content
3. save and accept a new revision
4. repeat the first step and compare the result

**Comment by elbotho** [comment]
first step is probably to find some example for each type.
http://de.serlo-staging.dev/___content and https://are-we-edtr-io-yet.serlo.org/ are resources for that.

**Comment by elbotho** [comment]
I prepared a simple playwright setup to automate this

**Comment by elbotho** [comment]
Those tests only check the fields that are used in the new frontend. No idea what else might get lost in the db ^^.

**Converted Entities**
- Events ✅ (first 🐛)
- ~Math Puzzle~
- Videos ✅
- Applets ✅ (another 🐛 👍 )
- CoursePages ✅
- Courses ✅ (two more fixed)
- Articles ✅ 
- Exercise ✅ (we got some diffs in the content, e.g. equations plugin, but I guess that's unrelated)
- ExerciseGroups ✅ (also content stuff)

**interim conclusion**
crazy amount of work. but worth it it seems 😅 

TODO: 
- [x] investigate failed uuids when staging resets
- [x] Check converted Revisions (`/uuid/revId` links) done ✅ (a bit sloppy tbh.)
- [x] Think about Unconverted Entities

**Unconverted Entries**
Just a quick test (because fallback to legacy would really be okay here).
After passing some more field for Courses it seems to work alright.
Remaining Exercise Groups are weird and should probably be deleted or converted with legacy :)

**Comment by elbotho** [comment]
Sooo after quite some effort: I'm pretty sure there are more bugs to be found.
And I hate to test on the community, especially since really frustrating errors could surface, but I don't really think I will find them with automated tests atm (with feasible effort)…
Let's introduce this carefully soon.
