### ISSUE TITLE
navigation: handle dropdowns

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#149]
The current frontend implementation seems to flatten the navigation entries, see e.g. the difference between `https://de.serlo.org/informatik` and `https://frontend.serlo.now.sh/informatik` (Neu hier? and Papierkorb should be grouped into `Bei Serlo-Informatik mitarbeiten`.

**Comment by Entkenntnis** [comment]
had some discussion with botho earlier about that and we silently agreed to leave out these dropdowns. The reason was, that the desktop implementation would be fine, but the mobile experience would be bad and we had no good idea how to make these entries visible on mobile (in addition to all the other levels of navigation)

**Comment by elbotho** [comment]
closing this in favour of #213
