### ISSUE TITLE
GCS: some autocompletions missing that were working days ago

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#153]
Update: The form itself is working fine, the real issue is that some phrases are just missing, like "satz des pythagoras" and I am sure that they worked some days ago :question: 

![grafik](https://user-images.githubusercontent.com/13507950/81007846-396b0980-8e52-11ea-9ec1-a17a60d9aa7d.png)

But results are available:

![grafik](https://user-images.githubusercontent.com/13507950/81046336-7538ba00-8eb8-11ea-8be1-9e2e42201d5b.png)

Maybe this will resolve itself ...

**Comment by elbotho** [comment]
hmmm, still not working.
not sure what to do here, because we don't really mess with the imported script.

Public test (no custom code) shows same behaviour:
https://cse.google.com/cse?cx=016022363195733463411:78jhtkzhbhc

since the results are all there, the main setup seems to be okay too (is also basically the same as  the old version).

We have the option to manually add suggestions (and synonyms).

**Comment by elbotho** [comment]
(also there is an option to integrate GCS with analytics a bit more which we don't use atm)
