### ISSUE TITLE
/serlo-geschichte not loading -> update splish-me content to edtr-io

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#157]
silently loads blank page:
https://frontend.serlo.now.sh/

**Comment by Entkenntnis** [comment]
"The last of its kind". This is a page in splish-me format, which the frontend does not support (and probably will not)

@yolo-bird Can somebody edit or convert this page?

**Comment by inyono** [comment]
Content composed using the Splish Editor will automatically be converted into Edtr.io State when editing / rendering (so it only needs a blank save to update the state in the Database). I can do query over the database before release so that we can find the remaining ones.

**Comment by Entkenntnis** [comment]
yeah, lets do it this way

**Comment by elbotho** [comment]
@simonkoehl could you just open and save the https://de.serlo.org/serlo-geschichte page? 
(I don't have the privileges)
Then we can move this issue out of the Milestone. Thanks!

**Comment by elbotho** [comment]
@inyono If you send me a list I can take care of the conversion

**Comment by yolo-bird** [comment]
Just converted serlo.org/serlo-geschichte. -> One Issue less... :D

**Comment by elbotho** [comment]
Thank you @yolo-bird !

**Comment by inyono** [comment]
@elbotho Okay, just run a database migration that automated most of the conversions for entities (did forget pages, though, sorry about that. Going to add that in the next update). Remaining entities:
- /124741 needs to be updated once
- /132698 uses some features that the new Editor doesn't support (namely inline code). Can't do too much about that at the moment :/
- There are a couple of older revisions that won't work in the frontend anymore since we couldn't convert the state automatically. When we are 100% frontend, we can remove them from the db.

I also purged the cache so that requests to those pages are up-to-date.

**Comment by elbotho** [comment]
@inyono Nice, thank you! 👍 
I'll check the pages and then close this issue.

**Comment by elbotho** [comment]
small follow up in #245 
rest is okay for now imo.
