### ISSUE TITLE
don't add new revision if there was no change

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1574]
the new implementation adds a new revision for every exercise/solution in a exercise-group - even if there was no change.

Do we have enough information to detect this and skip unchanges entites? This will keep the revision history cleaner.

There is also the option to move this check into the API?

**Comment by elbotho** [comment]
I talked with @kulla  and @hugotiburtino  about this. The API should check it, the frontend can check it to reduce requests.

https://github.com/serlo/frontend/blob/25f5b56f94ee874df7e6449aaaf51538afcafa57/src/helper/mutations/revision.ts#L396

Also the API should create entities for children that don't exist yet. That's why Create*Entity and Add*Entity will be merged.
