### ISSUE TITLE
Migration: Editing and creating of taxonomyTerms

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1576]
staging  is working fine, can also be deployed already. check for cf worker afterwards

**Comment by kulla** [comment]
In order to create a new taxonomy Element the following buttons shall be added (would create a child with `taxonomyType === "topic"` or `taxonomyType === "topicFolder"`): 

![2022-04-20-125042_617x398_scrot](https://user-images.githubusercontent.com/1327215/164215518-469539a9-64cf-4ce0-929b-cd6e473b5c8a.png)

**Comment by Entkenntnis** [comment]
link for Themenbereich (topic): `/taxonomy/term/create/4/[id]`

link for Aufgabenordner (topic folder): `/taxonomy/term/create/9/[id]`

should be doable

**Comment by Entkenntnis** [comment]
@kulla our current translations are "Bereich" and "Aufgabensammlung". Is this fine?

![grafik](https://user-images.githubusercontent.com/13507950/165082775-9541109e-13a5-41dd-a332-637ba46781e9.png)

**Comment by kulla** [comment]
> @kulla our current translations are "Bereich" and "Aufgabensammlung". Is this fine?

Use "Themenbereich" und "Aufgabensammlung"

**Comment by Entkenntnis** [comment]
fixed translation in crowd in (the string "folder" was unused)
