### ISSUE TITLE
Migration: Use API-endpoints for creating / editing taxonomy terms

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1628]
Currently we are still using the legacy endpoints to create/edit new taxonomy terms. The plan is to move this over to the API soon.

**Comment by Entkenntnis** [comment]
Some context and thoughs:

The url for adding a taxonomy term is: `/taxonomy/term/create/4/200247`

the parent id is `200247`, and type is `4` (the naming of the folders is unfortunately wrong, because I didn't understood it correctly)

Things get a bit hairy in a situation like this:

![grafik](https://user-images.githubusercontent.com/13507950/168766626-298d6324-1b5f-481d-9c97-1b07e83627e1.png)

What should we do with these "legacy" taxonomy terms? Should we convert ALL taxonomy terms (including language versions) into topic and topicFolder (= exercisefolder)? Maybe there is some logic connected to them...

The new endpoint is not supporting these legacy types, so we have to thing a bit about places like this. (e.g. because the shown menu is not in the frontend, we have to do some kind of remapping in the frontend.)

**Comment by Entkenntnis** [comment]
The table for reference:

```
mysql> select taxonomy.id, instance.name, type.name from taxonomy join type on taxonomy.type_id = type.id join instance on taxonomy.instance_id = instance.id where type.name in ("topic", "topic-folder");
+----+---------+--------------+
| id | name    | name         |
+----+---------+--------------+
|  4 | Deutsch | topic        |
| 16 | English | topic        |
| 33 | Tamil   | topic        |
| 42 | French  | topic        |
| 48 | Spanish | topic        |
| 53 | Hindi   | topic        |
|  9 | Deutsch | topic-folder |
| 19 | English | topic-folder |
| 36 | Tamil   | topic-folder |
| 45 | French  | topic-folder |
| 51 | Spanish | topic-folder |
| 56 | Hindi   | topic-folder |
+----+---------+--------------+
```

(info: there are many for types, e.g. locale, curriculum, etc...)

**Comment by kulla** [comment]
> What should we do with these "legacy" taxonomy terms? Should we convert ALL taxonomy terms (including language versions) into topic and topicFolder (= exercisefolder)? Maybe there is some logic connected to them...

Yes, my idea is that there is only "topic" and "topicFolder" in the future. With https://github.com/serlo/serlo.org-database-layer/issues/258 this is mapped to the right instance version before saving into the DB. In the past the different are used to help authors to create proper taxonomies (with some rules like "curriculum" must be a child of "local"). However those rules are complicated and made the experience bad for authors -> Thus we want to map all taxonomy types to "topic" and "topicFolder". @Entkenntnis My understanding is that there is no change between "topic" or "locale" or any non-folder type in the frontend, right?

**Comment by Entkenntnis** [comment]
https://github.com/serlo/frontend/pull/1674 adds an initial implementation fo this feature.
