### ISSUE TITLE
404 for some empty uuids

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1672]
uuids: 127596, 127455 (found on sentry)

results in 404, content is empty

I would expect an empty page instead if content is empty

**Comment by elbotho** [comment]
@Entkenntnis very weird, because it shows corrently on localhost.

![image](https://user-images.githubusercontent.com/1258870/168557369-c6ed3c91-c5bf-4a64-a609-ad72a309dfb1.png)

But the content is definitely incorrect in those cases.



Link to report: https://community.serlo.org/channel/software-features-and-bugs?msg=zvYrSffxbi7naeqsn
ping @CarolinJaser

**Comment by Entkenntnis** [comment]
this is fixed contentwise (title added) + edtr-io is not allowing empty titles, sooo I think we a fine for the moment
