### ISSUE TITLE
Backend: Create help page for serlo community admins

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1716]
Create a help page at the wiki ( https://github.com/serlo/frontend/wiki ) with instructions for Serlo community admins for

- [x] What to do when a new license shall be created or updated?
- [x] how to create a new taxonomy term below root / a new subject (write in #meta-software-requests)
- [x] What shall be done, when navigation, footer & co shall be updated?
- [x] How to make URL of entity (article, event, co) or page absolute? -> https://github.com/serlo/api.serlo.org/blob/main/packages/server/src/config/alias.ts

**Comment by Entkenntnis** [comment]
I am wondering if this is the scope of the frontend repo? Some of the above config's aren't frontend only. Maybe a google doc within the software unit is a better place for this documentation?

License short titles: https://github.com/serlo/frontend/blob/staging/src/fetcher/create-inline-license.tsx
All other data (+ managed by crowdin): https://github.com/serlo/frontend/tree/staging/src/data

**Comment by elbotho** [comment]
I created this document. I agree that a doc might be more suiteable. This way other people like Wolfgang can also update it.
https://docs.google.com/document/d/1pwrFtnKYE7SuQVl4RkGENj-lWLtxnir11aJIecJwYBc/edit?usp=sharing

It's not a thrilling read since it call for #meta-software-requests for most things, but it's a start :D

**Comment by elbotho** [comment]
@yolo-bird what would you say is a good folder to save this file in and where should we link to it?

**Comment by ghost** [comment]
Actually the best place to put it, would be the help page here: https://de.serlo.org/140475

If it is too much wip to put it out on serlo.org, the folder of the Begleitungs-Unit, would be a good place. 
Since it is community related, I think the better place to direct them is https://community.serlo.org/channel/software-features-and-bugs instead of slack. 
Can you give me edit rights for the document anyway?

**Comment by elbotho** [comment]
Thanks!

> Since it is community related, I think the better place to direct them is https://community.serlo.org/channel/software-features-and-bugs instead of slack.

are there community admins that are not team members?

**Comment by elbotho** [comment]
> folder of the Begleitungs-Unit, would be a good place

Maybe for now we do that. I don't have the rights to move it there. Can you do that as an editor?

**Comment by ghost** [comment]
> Thanks!
> 
> > Since it is community related, I think the better place to direct them is https://community.serlo.org/channel/software-features-and-bugs instead of slack.
> 
> are there community admins that are not team members?

I think at the moment they are, but in future it won't be the case anylonger. So I think it makes sense to do community related stuff in Rocket Chat instead of Slack...

**Comment by ghost** [comment]
> > folder of the Begleitungs-Unit, would be a good place
> 
> Maybe for now we do that. I don't have the rights to move it there. Can you do that as an editor?

Done. Who does the communication to the admins that this document does exist?

**Comment by kulla** [comment]
> Who does the communication to the admins that this document does exist?

U Begleitung -> you :smile:

**Comment by kulla** [comment]
> Actually the best place to put it, would be the help page here: https://de.serlo.org/140475

That's a decision U Begleitung can do. Inform us, when you have moved the document.
