### ISSUE TITLE
Use HTTP header X-SERLO-API

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#177]
With https://github.com/serlo/serlo.org-cloudflare-worker/pull/11 the cloudflare worker sends the HTTP-header `X-SERLO-API` which points to the graphql endpoint which shall be used. The frontend client should use this variable to determine the endpoint. The possible values are:

* `https://api.serlo-development.dev/graphql`
* `https://api.serlo-staging.dev/graphql`
* `https://api.serlo.org/graphql`

**Comment by Entkenntnis** [comment]
Thank you for passing down the api endpoint! Can you give me some pointers in which situations this distinction is important? This would affect how I would implement this.

**Comment by inyono** [comment]
You should use the X-SERLO-API header value pretty much everywhere, where you currently use api.serlo.org (possibly using a fallback when it is not defined). With that, we can handle breaking changes in the API correctly. Furthermore, this is important in the future when we have API requests that make changes to the database. Current behaviour:
- de.serlo-development.dev has X-SERLO-API value api.serlo-development.dev/graphql
- de.serlo-staging.dev has X-SERLO-API value api.serlo-staging.dev/graphql
- de.serlo.org has X-SERLO-API value api.serlo.org/graphql
- Requests to frontend.serlo.now.sh (or PR previews) do not have a X-SERLO-API value. For now, it is fine to use api.serlo.org. In the future, we'd probably default to api.serlo-development.dev instead so that users can try out mutations.

**Comment by Entkenntnis** [comment]
This issue is stale and can be closed.
