### ISSUE TITLE
kratos: Error message after signing in

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1854]
Steps to reproduce:

1. https://de.serlo-staging.dev/ in a private window
2. Log in with `kulla` and `123456`
3. A screen occurs with `Auch Webseiten machen mal Fehler…`

After going to the main page it seems that I am logged in though. However with https://github.com/serlo/frontend/issues/1853 there might be issues regarding this.

**Comment by hugotiburtino** [comment]
At the moment, we are supposed to be testing the new user management (see beta-testing doc, heading User Management, and [this](https://serlo.slack.com/archives/C0BMSC431/p1664836901027239) and [this](https://serlo.slack.com/archives/CEB781NCU/p1664837407845079) slack posts), and that should occur in a custom staging domain. If you need regular staging, please follow the instructions of the slack post in #meta_dev. 

Just an explanation: you are logged in because of hydra (since the old user management is done with OAuth2, that redirects you to the current staging domain). But the authentication through OAuth2 is to be used only for rocket chat, not for our frontend. That is why you get a 'You are not logged in' error when trying the playground.

So I would say, it is not an issue.
