### ISSUE TITLE
Use readable hrefs for links

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#194]
Currently the links use the content id in the hrefs.
I'd prefer the longer full links. 
@Entkenntnis Is there an elegant way to add that to the articleRenderer? 
https://github.com/serlo/frontend/blob/b8460970768e23223f2176729cc4417be188ba67/src/schema/articleRenderer.tsx#L148

**Comment by Entkenntnis** [comment]
unfortunately, the links are only stored as ids in the database, so the frontend is not able to do much about it (at least without doing some requests to the backend ...)

**Comment by elbotho** [comment]
@inyono would it be an option to store both the id and the full version of the hrefs in the db?

@Entkenntnis would it be an option to request the full version of the link for each link while building the page?

**Comment by elbotho** [comment]
Related Note: we should also probably add a [canonical link tag](https://de.wikipedia.org/wiki/Canonical_Link).

**Comment by inyono** [comment]
> would it be an option to store both the id and the full version of the hrefs in the db?

Nope, since the alias could change (when changing the title or by moving it in the taxonomy). Instead, we should use the API for that. You can query multiple alias with one request, e.g.
```graphql
{
  uuid1: uuid(id: 1855) {
    ... on Entity {
      alias
    }
  }
  uuid2: uuid(id: 90) 
    ... on Entity {
      alias
    }
  }
}
```
If needed, we might also add that to the api itself, so that there are two content fields (one for the editor with the raw data, one for rendering with pretty urls) that one can choose between.

> Related Note: we should also probably add a canonical link tag.
Shouldn't be needed as long as `/<id>` are handled as 301 redirects as done in the legacy system. We only need a canonical link tag for stuff like query params (e.g. as used in the content API)

**Comment by elbotho** [comment]
@inyono what solution do you prefer?
- a call to the api for the links in the content
- or adding the readable urls to the api?

**Comment by inyono** [comment]
Depends:
- If you need the functionality in other places, too (e.g. to prettify the URLs from the navigation or other places where you just have the id), we should probably do it in the frontend with a dedicated Link component that is able to handle this stuff (so we can just use them whenever we need pretty URLs).
- If not, and it's really only the content, I don't care too much. Probably still not super nice to handle it in the API since you need to be careful to use the correct state (pretty URLs shouldn't be used in the editor for example) and if we want to asynchronously load the editor over the rendered content (without having to transition to another page), we have to make another request to the API.
