### ISSUE TITLE
kratos: possible improvements

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1944]
- ~rocket chat: en users are redirected to german login page atm~ (backlog)
- ~Handle error '401 this account was disabled'~ (not sure, reopen if it occurs)
- ~rocket chat: rocket chat stays logged in if users logs out of kratos~ (expected)
- ~after successful verification, can we prefill the username?~ (not easily -> backlog?)

- [ ] rocket chat: redirect takes a long time and the is no info in the frontend view (blank page while api call I think)
- [x] `A valid session was detected and thus login is not possible. Did you forget to set `?refresh=true`?` is not translated yet

**Comment by hugotiburtino** [comment]
> rocket chat: rocket chat stays logged in if users logs out of kratos

yes, it is not a problem, [it is how OAuth works](https://stackoverflow.com/questions/12909332/how-to-logout-of-an-application-where-i-used-oauth2-to-login-with-google). Actually, we can't synchronize the logouts in the moment unless we do some hacks. Anyway, it is the current behavior at production.

FYI: I've put that in backlog.

**Comment by hugotiburtino** [comment]
> rocket chat: en users are redirected to german login page atm

You mean of course users whose previous visit was in the English instance.

It is also in prod so. In prod it is hardcoded to be redirected to German instance. I've made it to a generic `serlo-staging.dev/auth/oauth/login` in staging . But since in cloudflare worker it is hardcoded to redirect to the German instance, the cookie previousInstance changes to de. 
We could give to set the cookie previousInstance before, and *not* to set it in the login component.
An even better solution IMHO would be to correctly handle locale, location and instance in cloudflare worker.

**Comment by hugotiburtino** [comment]
> after successful verification, can we prefill the username?

Since you can't receive this information from [SelfServiceVerificationFlow](https://github.com/serlo/frontend/blob/e7863a56588949c68a0a8ccb483d0efc64c01e18/src/components/pages/auth/verification.tsx#L40) I only see following hack:
1. we put the username in the verification url.  
2. If kratos don't pass it on (as I'm certain it won't), when user hits https://github.com/serlo/frontend/blob/62fc5f6cdb8303e3530e3202b7ceda10d6e23b53/src/pages/api/.ory/%5B...paths%5D.ts we store the username somehow (local storage? Is it possible?)
3. Recover the info of 2 when user comes to the login page

By the way, SelfServiceVerificationFlow has a request_url! Same field is also to be found in other SelfService...Flow, we could simplify our redirections using that
