### ISSUE TITLE
Editor: newly created entity already as undo option

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2047]
e.g. https://de.serlo-staging.dev/entity/create/Article/60730
without interacting with the page undo is already possible (but does not do anything).
possibly upstream issue.

Does not happen when editing existing entites.

**Comment by Entkenntnis** [comment]
can confirm, not sure what is causing this. No harm here as the button is doing nothing, though ..

**Comment by Entkenntnis** [comment]
closing this issue because the impact is very low and it's not easy to fix:

- it's either an inssue with edtr-io or the serlo editor implementation, and I looked a while through the implementation and haven't found a definitive place where we are accidentally adding a mutation
- debugging it would take a lot of time that is not really worth it for this

-> maybe add it to one of the backlogs we have for this
