### ISSUE TITLE
testarea content indexed on search engine

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2236]
[report](https://serlo.slack.com/archives/C0BMSC431/p1679597603311469)

testarea is currently accessible through search engines. `no-index` is not set.

first I thought it's the `<meta name="robots" content="max-image-preview:large">` I introduced, but it seems might actually be the part that @Entkenntnis refactored today (#2225).
Having two meta robots entries should not really cause a problem. The less permissive rule should be used ([source](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag?hl=en#combined)).

that's something we should probably have a test for.

**Comment by elbotho** [comment]
confirmed:

testarticle http://localhost:3000/270714
`no-index` missing in current production branch and present in staging.

**Comment by Entkenntnis** [comment]
https://github.com/serlo/frontend/issues/2225 has indeed make the check more reliable, as it's not relying on the alias anymore.

Previously, we were assume that the testarea has the url `/community/106082/sandkasten`, but due to an redirect entry the url is currenty `/community/sandkasten` and that's why the check failed.

Basically, the bug got fixed 2h before the report :sweat_smile:
