### ISSUE TITLE
editor: fix bug on load

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2254]
This problem is occuring when loading the preview

![grafik](https://user-images.githubusercontent.com/13507950/229500464-250c55ac-c53d-4eba-8c37-0980e5a6eecd.png)

**Comment by hejtful** [comment]
The issue is caused by the difference between the previously used and current Slate version. In the old version, empty `Element` nodes were tolerated, while in the new version "[All `Element` nodes must contain at least one `Text` descendant](https://docs.slatejs.org/concepts/11-normalizing#built-in-constraints)".

The correct approach to this issue seems to be to [deserialize](https://docs.slatejs.org/concepts/10-serializing#deserializing) the nodes coming from the database and fill the empty `Element` nodes with `Text` nodes.
