### ISSUE TITLE
editor: toolbar is not longer restricted (e.g. in table)

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#2261]
Some plugins restrict the allowed text-tools. For example in table headers only link, code and formulas should be allowed.

before:
<img width="206" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/1258870/229535718-70bca068-d826-4b6d-8883-ecb44860a8e4.png">

now:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1258870/229535961-21d4f2ef-15f9-453b-b87b-4c63b849fc35.png">

**Comment by hejtful** [comment]
I could only find this being configured in the `serlo-table` and `box` plugins. If you're aware of some other places, or come across them in the future, please let me know.

Btw, the cause of the bug is a breaking change in the `plugin-text` API (`plugins` property was renamed to `controls` and its type was changed), which I forgot to report when communicating the release to @Entkenntnis . I'm sorry about that.

**Comment by elbotho** [comment]
All good. Easy enough fix. Thank you.
