### ISSUE TITLE
Have hardcoded order in the form for the registration

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#2292]
The order of elements in the staging environment changed after enabling OIDC

### Order of elements in staging
See https://de.serlo-staging.dev/auth/registration, Note that `Passwort` is in the beginning

![2023-04-12-105620_830x926_scrot](https://user-images.githubusercontent.com/1327215/231455565-1335a176-4d14-4fbd-a6f9-07b09149c5ca.png)

### Order of elements at production
See https://de.serlo.org/auth/registration
![2023-04-12-105608_839x870_scrot](https://user-images.githubusercontent.com/1327215/231456756-4f992c38-ae45-4bd2-b4a7-e89d7007f7d3.png)

### Expected behavior
Implement a fixed order of elements in the registration form

**Comment by elbotho** [comment]
ping @CodingDive this hack is very likely the culprit: 
https://github.com/serlo/frontend/blob/staging/src/components/pages/auth/registration.tsx#L33-L38

It's one of the hacks that keeps the dream of using the flow from kratos directly alive. But tbh. we were close to hardcoding the forms before. Since usually the forms do not change a lot I'm still okay with adapting the hack.

**Comment by elbotho** [comment]
Also: Why is there an additional "weiter" Button and privacy checkbox?

**Comment by CodingDive** [comment]
>Also: Why is there an additional "weiter" Button and privacy checkbox?

Already tracked here https://github.com/serlo/frontend/issues/2282 and working on it. I emphasize with your wish to put all of this stuff in a feature branch instead of ruining our staging environment. Right now we couldn't even deploy staging with all these issues..

**Comment by elbotho** [comment]
> Right now we couldn't even deploy staging with all these issues..

At least we need a way to hide the changes from prod.
