### ISSUE TITLE
Implement working Single Logout

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2296]
OIDC has an [front channel single logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html), which is made by an iframe.

So, you are v.g. on site identity-provider.example and calls in the iframe a logout endpoint of site oidc-client.org. 

The problem is that, in the iframe, not all cookies from site oidc-client.org are going to be sent, specially not the ones related to authentication session (in our case, `auth-session` and `ory_kratos_session`).

Is it possible to have to following behavior at all:
Every time the browser calls https://serlo-staging.dev/auth/single-logout, even inside an iframe, serlo blindly deletes the cookies `auth-session` and `ory_kratos_session`?

**Comment by elbotho** [comment]
Learnings and Ideas:

**Updating cookies from iframe** (does not work)
Chrome and other browsers killed the third-party-cookie (that's essentially what we would need).
So writing or reading the cookies is not possible without at least changing our cookie settings (and that would probably introduce actual security problems)

**LocalStorage** (meh)
E.g. storing a "pleaseLogMeOut" in localStorage that logs the user out the next time they are on serlo.org would be possible, but not very reliable. (Writing to localStorage in iframe seems to be blocked in incognito mode in chrome by default and can be deactivated as a browser setting). It's also not a real logout.

**Server Side** (only actual front-channel way)
We could build a server-side function that accepts a username (https://serlo-staging.dev/auth/single-logout?username=hugo) and revoke the kratos session (via the API for example). 
~`identity-provider.example` would have to provide the username (or other identifier) in this case.~
Since `Front-Channel Logout` requires the client to provide the logout url we can provide the user-identifier (username or other id) ourself and maybe also add an additional token.
Since we can't access the cookies we can not easily verify the session and people could possibly then use this endpoint to logout other users. Probably not a dealbreaker and endpoint access should be restricted to `identity-provider.example` anyway.

**Easiest for us** (not front-channel)
If instead of using the iframe approach the identity provider would redirect to us (and we would redirect back immediately) single logout would be trivial for us to implement.

**Comment by CodingDive** [comment]
Good ideas! As an extra option, we could also consider using the `BroadcastChannel` to communicate with the main serlo tab. If no other logged in Serlo tab exists, maybe there is a way to utilize service workers to either delete the cookies directly (the service worker doesn't directly have access to cookies, only can subscribe to them https://developer.mozilla.org/en-US/docs/Web/API/CookieStoreManager but we could send a FETCH request to the server to do so), or to put the logout message in a queue and log out the user as soon as they'd open the app.

**Comment by hugotiburtino** [comment]
Thanks for your ideas @elbotho . Let's discuss the solutions. I can already say that redirecting to us is not an option, because the oidc front channel logout spec does not allow it (and it is reasonable, because the identity provider may have to logout many services providers at the same time)

**Comment by elbotho** [comment]
Fully agree.

**Proposal based on "Server Side":**

- frontend: on SSO we provide an logout url with an user identifier (username or other id) (and possibly a token) (e.g. https://serlo-staging.dev/auth/single-logout?username=hugo)
- frontend: server-side route that accepts this user identifier and calls the API (could be skipped if we can access the api directly)
- api: [revokes kratos user session](https://www.ory.sh/docs/kratos/session-management/list-revoke-get-sessions#revoking-a-session) ([draft pr](https://github.com/serlo/api.serlo.org/pull/835))

Additional steps to reduce misuse (like logging out other users):
- endpoint should be restricted to requests from `identity-provider.example`
- we could provide a token within the the logout url that we can then check that in api or frontend (not sure what that would consist of)

**Comment by hugotiburtino** [comment]
_Analysing the Server Side proposal_

We cannot count with a custom query param (v.g. `?username=hugo`), since the Identity Provider in this case is a Keycloak instance which isn't easily configurable and I don't think their developers would worry about making a special logout just for us. The following query params are provided: `iss` ("issuer", base url of the IdP)  and `sid` ("session_id", the identifier in the IdP of this specific session. It was provided also at the login under the name `session_state`).

Besides that, I see a lot of backend calls and logic in this proposal, so that it is easier to implement back channel logout instead. 

_LogMeOut Proposal: reloaded_
I actually think this idea could work: it is easy, only depends on browser and we don't need to mess with the auth cookies. The only thing I would change is to put it as a cookie and not in LocalStorage. This cookie doesn't have to be secure at all, it has to be just like `previousInstance` cookie (which on its turn is sent in the iframe), so that (*I hope*) it can be set also after receiving the call from an iframe. 
Now, we would just 1. as you pointed out @elbotho, secure the endpoint, in order to just work if the specific logout call was made by the IdP in question (we could maybe even check if the `sid` is the same as the provided in the login) and 2. manage this logMeOut cookie in order to not clash with other scenarios (v.g. the user logs in again).

@CodingDive I'm not sure if I understood your BroadcastChannel proposal, let's discuss it in our meeting

edit: correction: not subject but issuer

**Comment by elbotho** [comment]
Server Side:
I misunderstood it first but now I'm pretty sure that we have to provide the logout url so we don't have to care about their implementation and can add the identifiers and tokens we like.

> Besides that, I see a lot of backend calls and logic in this proposal, so that it is easier to implement back channel logout instead.

That might very well be. I have not looked into that.

**Comment by elbotho** [comment]
LogMeOut:
We'd have to investigate the support of unsecure cookie vs localhost in this thirdparty context but both could work (and both could potentially be blocked by the browser).
It's still not super reliable (and not a real logout and would not work on multiple devices for example) but it's a lot easier to implement I guess?

**Comment by kulla** [comment]
As discussed in the recent meeting: We will directly implement a backchannel logout
