### ISSUE TITLE
regression: save bar is overlapping hovering toolbar

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2555]
https://de.serlo-staging.dev/entity/create/Exercise/23869:

![grafik](https://github.com/serlo/frontend/assets/13507950/8dcefd6d-83d5-4c4c-8472-1e2661b6372d)

works in [production](https://de.serlo.org/entity/create/Exercise/23869).

@elbotho looks like some z-index issue ...

**Comment by Entkenntnis** [comment]
the controls-bar has a z-index of 100, the hovering toolbar has z-index of 95. It looks easy to fix by changing one of them.

Do you have context which change is better?

**Comment by elbotho** [comment]
> Do you have context which change is better?

I'm not sure what started it but I have a cascade of z-Index problems right now :) 
It's something that we should probably have a concept for at some point.

In this case it is even intended that the toolbar is overlapped tbh. Otherwise we have a weird effect where the "save-bar" moves above the selected text but below the toolbar. 
I would solve this with a `margin-top`.

**Comment by Entkenntnis** [comment]
thats a good idea, too!
