### ISSUE TITLE
complete input exercise implementation

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#261]
Some bits are missing from input exercises:

- normalize input
- InputExpressionEqualMatchChallenge (algebra.js)

https://github.com/edtr-io/edtr-io/blob/master/packages/plugins/input-exercise/src/renderer.tsx

**Comment by elbotho** [comment]
https://github.com/edtr-io/edtr-io/blob/3a848b2717849585650bc5246a48b391c54b3964/packages/plugins/input-exercise/src/renderer.tsx#L46

**Comment by elbotho** [comment]
@Entkenntnis did you find some examples to test that maybe?

**Comment by elbotho** [comment]
or @yolo-bird can you think of some input-ex collections that might use advanced stuff?

**Comment by yolo-bird** [comment]
there are some @elbotho, but I can't remember any out of the top of my head. Maybe you could ask the crowd in #u_begleitung.

**Comment by Entkenntnis** [comment]
Ok, here is an example (edtr-io): https://de.serlo.org/63833

Solution is `0.5*(x-1)^2+1`, but you can type any equivalent mathematical expression, e.g. `0.5*x^2-x+1.5`.

**Comment by elbotho** [comment]
https://github.com/nicolewhite/algebra.js is archived and not updated since three years. 
Any objections to continue using it, or any small alternatives that come to mind?

For now I'll go ahead with it.

other options that might work: 
- https://mathjs.org/ and hope tree shaking makes the size manageable
- https://github.com/bylexus/fparse
- https://www.npmjs.com/package/math-expression-evaluator
- https://github.com/handsontable/formula-parser
