### ISSUE TITLE
placeholder text misaligned

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2762]
cursor is in the line above the placeholder:

![grafik](https://github.com/serlo/frontend/assets/13507950/63ccf729-ca64-4f97-88aa-cc6438d22221)

**Comment by elbotho** [comment]
which branch, uuid and browser?

**Comment by Entkenntnis** [comment]
reproduction:

- open https://de.serlo-staging.dev/entity/repository/add-revision/1553 (ff, windows)
- click on the whitespace above the list
- the placeholder is misaligned

**Comment by Entkenntnis** [comment]
not reproducable in chrome, though

**Comment by elbotho** [comment]
thanks! can see it in ff, too.

**Comment by hejtful** [comment]
This is caused by two links without text, just before the list (see screenshot). A "Backspace" key press removes these empty links and fixes the content.

<img width="1763" alt="Screenshot 2023-08-22 at 15 57 45" src="https://github.com/serlo/frontend/assets/13198821/64705c77-be40-45a5-9697-760fdddb74c7">

**Comment by elbotho** [comment]
fixed the content in staging and production. 
also changed the behaviour back so placeholder only shows when content is empty in multimedia plugin.
