### ISSUE TITLE
editor: Slate error when merging a text plugin with another text plugin that has a list

### ISSUE THREAD

**Issue by hejtful** [serlo/frontend#2798]
In the attached video, the beginning of "image" headline is selected, and "Backspace" key is pressed to merge the two text plugins. A Slate error is thrown.

Relevant files:
- https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/text/hooks/use-editable-key-down-handler.tsx#L136
- https://github.com/serlo/frontend/blob/staging/src/serlo-editor/plugins/text/utils/document.ts#L54

Note: Might be worth adding an e2e test for this case.

https://github.com/serlo/frontend/assets/13198821/e63699cb-96cd-477e-8abb-2e9d39dfb773

**Comment by Entkenntnis** [comment]
@AsterMiha If you don't mind, could you give a small update on this? (if you are actively working on it)

**Comment by AsterMiha** [comment]
> @AsterMiha If you don't mind, could you give a small update on this? (if you are actively working on it)

It turns out that the error is only happening when the first element in the previous block we try to merge with has a list as its first element. I'll add a normalization case to also add an empty text line if the first element would otherwise be a list and unless I missed something it should be fixed soon!
