### ISSUE TITLE
idea: mock auth on env=development

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#357]
I understand that oauth quite an involved protocol and setting it up requires the current serlo.org dev environment.

Nevertheless it would be cool to be able to test auth ui features in development. So my question: Do we want to create a mock auth implementation that is only availabe for development environments? (e.g. localhost)

It would create a "dummy" token, where you can decide which user and which roles you want to enable, and the ui can then adapt to it. GraphQL requests would not work though, but these can be tested on serlo-staging.dev (hopefully).

If we code the mock properly, it wouldn't even show up in the production builds.

**Comment by elbotho** [comment]
relates to #327

**Comment by inyono** [comment]
As we can only mock the UI anyways (since the API would require a real token), I'd prefer the Storybook route (#327) since
- It forces us to decouple the components from the actual token implementation.
- "Mock" code is not part of the production code, w/o us having to watch out for that.
- We could also use the stories for unit / e2e tests.

I'm not entirely sure how we are going to handle local development of stuff that needs to interact with the API, yet (e.g. editing stuff with the editor) w/o running the API locally, too. For this specific case, we could add `http://localhost:3000` to Hydra in the staging environment so that one can log in to localhost, too.

**Comment by Entkenntnis** [comment]
Your last remarks sound like a very interesting option: So is it technically possible to use the staging hydra server to log in on `localhost:3000`? This would mean we can have *real* log-in in development, I'm opening a new issue for this: #364 

Otherwise, I think we can close this and keep the discussion in #327.
