### ISSUE TITLE
Complete Translations

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#434]
Every language has one file with all its strings (https://github.com/serlo/frontend/tree/staging/src/data). The strings are splitted into four types:

- loaded for every page of the instance (instance data)
- loaded only for the landing page (landing data)
- loaded only for logged in users (logged in data)
- loaded only on the server (server data)

For the current milestone, it would be enough if these files are translated. In the long-term, reintegration with crowdin (or similiar) would be great.

**Comment by elbotho** [comment]
Branch is here: https://github.com/serlo/frontend/tree/crowdin-integration

It's not as pretty as I hoped it would be.
I had to move the menu data to a second file, because it is not structured the same way across languages.
we need upload those independently to use crowdin for those.

but now the rest of the strings can be edited and crowdin exports valid ts files back.

TODO:
- [x] There is a bug with german translations where umlauts get messed up. Waiting for the support to get back to me here, but actually it seems to work with the GitHub integration. Fingers crossed.
- [x] currently all targeted languages (53 of them) get exported and this make quite a mess. [Lots of commits](https://github.com/serlo/frontend/pull/437). Also this currently breaks lint:tsc and therefore the build

**Comment by elbotho** [comment]
Okay, translations are done, but we keep coming up with new stuff so we also need translations for:

- [x] notifications (ready for translation now)
- [x] authed menus (ready for translation now)
- [x] comment system (ready for translation now)

**Comment by elbotho** [comment]
Okay, I'll close this, because Crowdin is set up now and the workflow seems to work okay. 
Now we need to wait for the translations and need to keep i18n in mind for new features.
Follow up in #483.
