### ISSUE TITLE
RFC: Just don't show default license for exercises and injections

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#436]
### Suggestion:

**Default case:** We only show license information at the bottom of an entity.
![image](https://user-images.githubusercontent.com/1258870/89166946-121ff780-d57b-11ea-9c33-03ec90f9a0dc.png)

So we don't display it for embedded exercises, solutions, exercise groups, images and injections…
We might need to change the text to something like "Wenn nicht anders angegeben…"

---

**Exception:** If the license differs from CC BY-SA 4.0 we display a short text and an icon ([not the cc icon](#435) 😄) with title attribute and some other way for mobile (let's see)

![image](https://user-images.githubusercontent.com/1258870/89167092-42679600-d57b-11ea-84a7-08b9574766b9.png)

---
Reasoning: I don't see a benefit of showing all of those CC icons especially for exercise collections they create a lot of visual clutter atm. 

Any objections, ideas? Did I miss something?

ping @inyono @yolo-bird @simonkoehl 
related #269

**Comment by Entkenntnis** [comment]
Previous discussion: https://github.com/serlo/frontend/issues/108

**Comment by ghost** [comment]
So just to give you a few facts. Currently there are 2184 entities licensed not under the CC-BY-SA 4.0:
- 2160 instructions of text exercises and text-excercise groups (the solutions are all under  CC-BY-SA 4.0)
- 24 videos

In the unit begleitung we would like to reduce the number of entitites under our standard license. We expect to reduce the number of videos to 2, so here we could just write the separate license in the video description and we will not need some design solution imho.
If we succeed with the exercises we will need a way of communicating the "by" in the standard license clearly, if the exercise was created by somebody else. 

For exercises embedded via injection I would still show the license if it differs from our standard one.

**Comment by elbotho** [comment]
@yolo-bird okay so we especially mark content that is not CC-BY-SA und also content where the license is CC-BY-SA but Serlo is not the source to be attributed. Good for you?

@simonkoehl there were no real objections so far, what do you think about this?

**Comment by Entkenntnis** [comment]
If there is no objection, I would suggest that we start trying this with topic folders: In a "topicFolder" or "curriculumTopicFolder", we add a CC-BY-SA license notice to the bottom (equals our license id 1) and remove all other license notices with id 1 within the exercises. All other license will stay visible.

@elbotho This feels straight forward to implement, do you want to create a PR for it?

An example: An the page https://de.serlo.org/mathe/stochastik/relative-h%C3%A4ufigkeit-wahrscheinlichkeit/aufgaben-thema-laplace-experiment we can remove about 90% of all license notices, because they are our standard license.

**Comment by ghost** [comment]
@elbotho this sounds great!

**Comment by simonkoehl** [comment]
I like the suggestion @elbotho . Imo we even don't have to include something like "sofern nicht anders angegeben" on every page because it is the linked ("Was bedeutet das") more detailed agreement that counts. Behind the link as well as in our terms&conditions we should point out, that our open licences only apply where not noted different.

**Comment by inyono** [comment]
cc @kulla regarding image source plugin. Might need to touch the "global" license notice in the footer so that it's clear where the license information for the images is.

**Comment by Entkenntnis** [comment]
~~We could also add "Lizenz" to the footer to make sure everybody can find the relevant information.~~

Edit 1: Ups, we already have a global license page: https://de.serlo-staging.dev/terms (and it looks ok, we already say (kind a) that all content is under cc except otherwise noted.

**Comment by Entkenntnis** [comment]
implemented in #517
