### ISSUE TITLE
Changes in "Sandkasten" only visible after reload

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#468]
1. Visit https://de.serlo-staging.dev/community/sandkasten/test
2. Login
3. Edit something, save.
4. You still see old content.
5. Reload
6. New content is available.

**Comment by inyono** [comment]
Seems like intended stale-while-revalidate behaviour. There might be a couple of ways we can work around that (Brain storming):
- When user is logged in, refetch newer content on client (e.g. using https://swr.vercel.app/ so it gets also revalidated on tab focus). Might run into a race condition (e.g. when the content is refetched before background request is done).
- Ignore the issue: since most edits should go to review anyways, it might be enough to show a message like: "The revision has been created and will get reviewed" (with review) or "The revision has been created and will be live shortly" (w/o review).
- Instead of redirecting to the article, redirect to the revision. This way, we shouldn't have cache problems (since Vercel shouldn't have a cache for the new revision) and users can also see the rendered content for revisions that will be reviewed.
- Redo the request on client side but pass token. This should disable cache altogether.
- Pass the current revision id when saving so that we can refetch the current revision on client if possible.
- Use https://swr.vercel.app/ to only fetch the current revision id (on refocus tab, once per minute, ...). If the current revision id doesn't match anymore, tell the user that the content has a newer revision and offer to reload the content.

It probably gets easier when we actually have the request in the API and do stuff client-side. Then we don't need to work around the SSR cache and also have all the necessary information in the frontend (what should be the new current revision id, etc.) to refetch newer data.

**Comment by Entkenntnis** [comment]
Fortunately, this is not a blocker for the current milestone, as the "normal" flow is through review - and we can always say something like "will be live shortly".

**Comment by Entkenntnis** [comment]
related to #355

**Comment by Entkenntnis** [comment]
Closing, because this is inactive atm.
