### ISSUE TITLE
Image Magnific Plugin: Broken in new content

### ISSUE THREAD

**Issue by metzgaria** [serlo/frontend#548]
Images don't maximize on click
(reported by author hxwalther)

**Comment by Entkenntnis** [comment]
We had a draft here: https://github.com/serlo/frontend/pull/242

But it was postponed...

**Comment by elbotho** [comment]
~will start this when #564 is done~ added to #564.
This should be the only place (for edtr-io content) where images are not full width, right?

**Comment by kulla** [comment]
Is this implemented? When I click on a image at https://de.serlo-staging.dev/mathe/zahlen-gr%C3%B6%C3%9Fen/grundrechenarten/addition/addition it does not maximize... Am I missing something?

**Comment by elbotho** [comment]
@kulla jup, this is only implemented for the "Multimedia-Explanations" because in the edtr there is currently no other way to display images smaller than full width. I chose not to open a lightbox for those images, would not make sense most of the time. [Working example](https://de.serlo-staging.dev/community/sandkasten/politik/bundestag/abgeordnete)

**Comment by kulla** [comment]
> @kulla jup, this is only implemented for the "Multimedia-Explanations" because in the edtr there is currently no other way to display images smaller than full width. I chose not to open a lightbox for those images, would not make sense most of the time. [Working example](https://de.serlo-staging.dev/community/sandkasten/politik/bundestag/abgeordnete)

:+1: (for displaying sources to images I need them to other images as well -> however this has time since I am still planing this feature)
