### ISSUE TITLE
maybe add more info to auth

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#576]
For community features (#479) we maybe need some more information about the user.

We should evaluate if we need this information in other places as well, so we can decide if we should add an api call to auth (e.g. after logging in).

The information in question is the user id and activeDonor, activeReviewer and activeAuthor fields.

**Comment by elbotho** [comment]
memo: user id should be accessible through profile data

**Comment by elbotho** [comment]
status: waiting for api to support querying by username

**Comment by inyono** [comment]
That's already implemented:
```graphql
{
  uuid(alias: { instance: de, path: "/user/profile/inyono" }) {
    ... on User {
      username
    }
  }
}
```

**Comment by elbotho** [comment]
ah nice, thanks @inyono.
would `use-auth.ts` be a good place to query and add additional user data?

**Comment by inyono** [comment]
I'd add an extra hook for that, maybe `use-user-data` or something. Reason: we want `useAuth` to be fast (to decide whether the user is logged in or not), so we don't want to have an API call there.

For your specific use case, you might even think about putting the logic into a `UserLink` component or something since you probably want to do that not only for the logged in user, but also for arbitrary users (expect the user profile, but there you acquire the user anyways). And - if you want - you can even SSR this stuff (in contrast to the auth info).

**Comment by elbotho** [comment]
@inyono thank you, `use-user-data` sound like a great idea.

We have a UserLink already. This question arose while working on the profiles and relates to the logged in users info only.
I will close this, then we can dig it up again if it becomes relevant someplace else.

**Comment by elbotho** [comment]
(added in 0dcc273)
