### ISSUE TITLE
Navigation in spanish-page not right

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#608]
On here https://es.serlo.org/matem%C3%A1ticas (and in the whole matematicas-topic) the navigation does not include the point " "¿Eres nuevo aquí?" which is implemented in the backend and shown in the old frontend.

**Comment by kulla** [comment]
My first guess: A listener is missing in the serlo.org backend when the navigation was edited.

**Comment by inyono** [comment]
We (intentionally) don't have a listener for the navigation since the navigation API request is quite expensive and a listener would trigger a couple of times (since even adding a single page to the navigation has quite some changes in the background). Since we don't change the navigation as often anyways (and think of removing the navigation backend later), we decided to leave it like that for now and manually reset the cache after changes. Another approach: we could do a time-based caching for the navigation. In this case, we should make sure that the cache is updated asynchronously in the background (since the request is expensive like said above).

I just deleted the cache for the spanish navigation, it should work now.

**Comment by elbotho** [comment]
@inyono could we (easily) provide a link that resets the cache?

**Comment by inyono** [comment]
Not yet, no. We have a GraphQL mutation for that and we could give specific users / user groups access to that.

**Comment by jakobwes** [comment]
Thank you for resetting the cache. Now it works!
