### ISSUE TITLE
Google custom-search is in German.

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#612]
Is it possible to adapt the Google Custom- ("Serlo")-search to the different language-versions? At the moment it is still shown in German everywhere.

**Comment by elbotho** [comment]
@jakobwes So the best case would be to have the interface and the results only in the instance-language right?
In that case we need an extra engine for each instance at https://programmablesearchengine.google.com

**Comment by jakobwes** [comment]
@elbotho yes that would be the absolutely ideal case!

**Comment by elbotho** [comment]
@jakobwes added spanish search in #661.
**Testlinks:**
https://frontend-git-spanish-search.serlo.now.sh/es/search?q=sobre
https://frontend-git-spanish-search.serlo.now.sh/es

What will not work yet: 
- [x] Autocomplete will probably take some time to have any or good suggestions
- [ ] Currently it will display ads, hopefully Google switches this search over to NGO status as well
- [x] When using the search you might end up on the german version, this is only a problem in this preview and should work in staging
- [x] only spanish supported. What other languages would make sense?

**Comment by inyono** [comment]
> * only spanish supported. What other languages would make sense?

We have 6 supported instances at the moment:
```ts
export enum Instance {
  De = 'de',
  En = 'en',
  Es = 'es',
  Fr = 'fr',
  Hi = 'hi',
  Ta = 'ta'
}
```
I'd say, either add a version for each of those or at least fall back to an English one if we don't have one yet.

**Comment by jakobwes** [comment]
Thank you for implementing. That looks amazing @elbotho (and btw. I also really love the consent-banner for the search: that's a cool solution to the data-privacy problem) :+1:

**Comment by elbotho** [comment]
@jakobwes thanks for the praise 😊 
~what do you say to the "what other languages?" question?~ 
nevermind, since it takes some days (& possibly searches) to unlock ngo and populate autocomplete I created all missing instance search engines now.

### Memo for future @elbotho 
Hope you're still awesome. 🍵 
For a new search engine:
- Just [create it](https://programmablesearchengine.google.com/) choosing the right language and subdomain. 
- Download Search engine context XML (setup > advanced) 
- Copy most of the settings of an working one, translate labels with strings from crowdin
- reupload
- add id to frontend
- ah yes & the ngo status works like this: admin of [google nonprofits](https://www.google.com/nonprofits/) has to be owner or verified admin of the search, then google will manually check after some days and then ads can be deactivated
