### ISSUE TITLE
Embedded YouTube-video has playing-error in new frontend

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#613]
In https://es.serlo.org/serlo the embedded YouTube-video works fine in the old frontend, but not in the new one. Is this related to the fact that the static page is created with the old editor?

**Comment by elbotho** [comment]
@jakobwes Thank you for reporting – weird, will need investigation… 🔍

**Comment by elbotho** [comment]
@jakobwes okay, found the problem. 
In the new frontend we extract the youtube id from the given url and build our own share url with all the features we want.
There was an error in that code that is now fixed (e798bfe6b394063ca608ce1d17a9d9e2886f7ab4) (will deploy later today).

So there is currently no support for additional parameters any more (like the subtitle activation and language setting on that video).
I think that is something that we want to keep this way in general, because this way no unwanted features can be activated by the authors.
But in this case it's also useful… hmm. Could you open another issue for that if you think you need it?
Thank you!
