### ISSUE TITLE
Allow support for additional parameters in YouTube-Urls

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#640]
Follow up on #613. For the internationalization and cross-platform work it is fairly important for us to at least be able to use a subtitle and language-setting-parameter in the embedding of YouTube-videos. One usecase the video in here, currently showing a playing-error: https://es.serlo.org/serlo

**Comment by elbotho** [comment]
@jakobwes is the language setting always set to the language of the instance?

**Comment by inyono** [comment]
Can we solve that without having the authors to do anything? I.e. when video language != instance, then show subtitles?

**Comment by elbotho** [comment]
@inyono  Thought about this as well. But without a lot more effort (namely youtube api implementation) I don't think we can get the video language (and it seems it's also not always set …)

Those are the relevant settings ([source](https://developers.google.com/youtube/player_parameters?csw=1)):
cc_lang_pref | This parameter specifies the default language that the player will use to display captions. Set the parameter's value to an ISO 639-1 two-letter language code.If you use this parameter and also set the cc_load_policy parameter to 1, then the player will show captions in the specified language when the player loads. If you do not also set the cc_load_policy parameter, then captions will not display by default, but will display in the specified language if the user opts to turn captions on.
-- | --
cc_load_policy | Setting the parameter's value to 1 causes closed captions to be shown by default, even if the user has turned captions off. The default behavior is based on user preference.

So we can preset the language, but not really know if subtitles should be shown without the author.
Since it's probably the case, that most videos should not show subtitles, I'd implement something simple that detects the `cc_load_policy` parameter.

**Comment by inyono** [comment]
Mh... Well, we need to think about if / when we want to support that in Edtr.io content, too ("luckily", since this is a static page this is content still created with the legacy editor). While this makes sense for this specific use case, I'd like to avoid adding this as an option to every video... (especially since this would be different per video platform).

**Comment by elbotho** [comment]
@inyono how about just not disallowing additional url parameters (status quo)? 
This way we can cherry pick what we want to support in the frontend (and keep ignoring the rest).

**Comment by inyono** [comment]
That's pretty much the case at the moment for Edtr.io-created content. But doesn't solve this use case.

Edit: or do you mean we shouldn't remove all URL parameters (which we basically do now) and instead have an (undocumented) feature that we save the stuff including url parameters and then normalize it somewhere (while allowing some parameters)?

**Comment by elbotho** [comment]
I think it does. Please explain.

**Comment by elbotho** [comment]
Ah yes, that's what I mean. Because of the legacy way the frontend extracts the YouTube ids atm. so this should work.

and yes, undocumented. Or documented in the serlo guidelines would be enough for this special use case imho.

**Comment by inyono** [comment]
Okay, just checked what we currently do in Edtr.io: Basically, we do the same as we do in the legacy system / frontend: we persist the URL but when rendering, we only extract the video ID from the URL. So if we want to support this, we'd definitely need to change the Edtr.io plugin, too, so that one can customize the normalize behavior.

**Comment by inyono** [comment]
Edtr.io follow up issue: https://github.com/edtr-io/edtr-io/issues/330. We need to keep that in mind when we switch static pages to Edtr.io content and/or add Edtr.io to the frontend. But for now, your solution should be good enough.

**Comment by jakobwes** [comment]
Thank you so much for the fix/feature @elbotho, @inyono. This is gonna motivate the spanish team!
