### ISSUE TITLE
Try out DM Sans

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#741]
Follow-up of https://github.com/serlo/frontend/issues/159#issuecomment-755323032

I really like the DM Sans and would be interested in how this looks like in our current frontend.

@elbotho Maybe you can create a demo PR for this?

**Comment by elbotho** [comment]
Sorry, tbh I'm reluctant to spend time on design right now (that's why I closed the old one).
For me [this is enough](https://frontend-git-font-chooser.dal123.now.sh/1707?font=DM+Sans&spacing=0.01) of a prototype.
(you can add the ?font=DM+Sans&spacing=0.01 to any url in https://frontend-git-font-chooser.dal123.now.sh)

**Comment by Entkenntnis** [comment]
Ok, that alright. I was still curious and created a up-to-date prototype to see how it looks like (#742).

@simonkoehl I can remember that you had some opinions about the font. Do you want to take a look at https://frontend-git-dm-sans-test.serlo.now.sh/ to see if this font would solve these issues?

**Comment by Entkenntnis** [comment]
Closing this issue for now, because its low priority, but it's good to know that we have a fallback option.
