### ISSUE TITLE
Figure out how to best handle revalidation on mutations

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#853]
We currently use `getStaticProps` with the shortest `revalidate` setting of 1s. 
This is too short for almost all situations but mutations where it actually delays instant revalidation.

Vercel will probably release a feature soon, that will allow us to manually revalidate:
> FWIW we are working on an on-demand invalidation API that we’re hoping to post a RFC for in the next couple months.

But we could also think about fixes/compromises in the meantime since this is causing some UX problems.

**Comment by inyono** [comment]
> This is too short for almost all situations

Just an FYI: this is done intentionally since a higher SWR cache time wouldn't improve the situation for the end user. So there is no reason to increase `revalidate`.

First ideas for approaches for the actual issue:
- We could have a local storage of the data that we fill when we do API requests and update accordingly when the user does a mutation. This way, we shouldn't need to hard reload.
- We maybe could define an additional API route that doesn't cache at all (that we could use after the user mutated something). We'd probably be better of just returning the data in the mutation itself then, though.

**Comment by elbotho** [comment]
Thoughts:
- A point for reloading (btw. a very soft reload :) is that we don't have to implement any query or data mutation logic in the frontend, it's just the same logic that was used to display the page the first time.

- For threads we use Vercel SWR and that works pretty nicely, even tough we fetch all data again on a mutation.

**Comment by Entkenntnis** [comment]
For the time being, we will stick with 1s revalidation and reload content after mutations or use vercel swr. This is probably the simplest solution for this issue atm.

**Comment by elbotho** [comment]
[Update](https://github.com/vercel/next.js/discussions/11552#discussioncomment-646963):
> Hey everyone! There's been a lot of discussion here about programmatically purging routes that have been generated with ISR. We're happy to share we're actively working on this now 😄 We've spent the time since this feature launched evaluating options and have come up with a solution we think you'll love.
> 
> **Stay tuned! 🚀**
