### ISSUE TITLE
Lazy component not loading when element is visible on page load

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#865]
Placeholder visible after page load, only loads after scrolling.

e.g.
https://de.serlo-staging.dev/mathe/1565/sinus-kosinus-und-tangens
![image](https://user-images.githubusercontent.com/1258870/107023001-539d9380-67a6-11eb-86d8-a1f1c16e5fd8.png)

**Comment by Entkenntnis** [comment]
The reason is that the placeholder for math is 200px high (much higher most formulas). So if math wrappers load, the layout shift is quite big and the formulas below are not triggered for rendering.

A quickfix would be to reduce the height of the placeholder for math formulas so less shifting occurs?

**Comment by elbotho** [comment]
Jup, probably a good idea.

**Comment by elbotho** [comment]
maybe we should increase the `offset` of react-lazyload a bit as well. 

And as a last resort there is [`forceCheck`](https://www.npmjs.com/package/react-lazyload#forcecheck).

**Comment by elbotho** [comment]
@Entkenntnis can't reproduce locally. interesting!

**Comment by Entkenntnis** [comment]
I can reproduce it locally. interesting..
