### ISSUE TITLE
horizon

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#9]

**Comment by elbotho** [comment]
#22 also affects Horizon

**Comment by elbotho** [comment]
I'd suggest using real headers instead of styling an `<p>` as an header.
``` html
<p class="Horizon__Headline-njfljx-3 hHOxip">Öfters hier?</p>
```

also the text should not be included in the link imho.

**Comment by theMetalkate** [comment]
Hey, thanks for your feedback. I changed the headline to a h4 tag (not higher so it will not interrupt with the more important SEO tags).
With the second part I do not agree. Users are used to it that a big area is linked (also the whole area is linked at the moment on the live platform). It is also easier to click on it but I agree that it wasn't clear that it is a link because some UX was missing. I add a color change and box shadow on hover now. Please take a look at the merge request:
https://github.com/serlo/frontend/pull/28

**Comment by elbotho** [comment]
@theMetalkate nice, way better. good enough for now.
Details if you feel like it:
- make sure the first box starts on the same line as the content (might need some negative margin because of the hover-shadow)
- Personally I'd like a little more space between the boxes (on desktop)

**Comment by theMetalkate** [comment]
@elbotho the max width of the content is 800px right? Maybe I should also reduce the max size to 800px than with the changes you mentioned

**Comment by elbotho** [comment]
@theMetalkate not completely sure if I understand, but I'd say no, let the parent decide the width.

**Comment by Entkenntnis** [comment]
PR merged
