### ISSUE TITLE
Error on https://de.serlo.org/mathe/54253/doppelbruch

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#948]
I get the following error on https://de.serlo.org/mathe/54253/doppelbruch:

![Screenshot from 2021-03-22 18-45-08](https://user-images.githubusercontent.com/13718882/112042205-2aab4500-8b3f-11eb-819d-3b9f74f63ce0.png)

**Comment by Entkenntnis** [comment]
we are working on it!

**Comment by elbotho** [comment]
Id of injection is [54318](https://de.serlo.org/mathe/54318/54318).
Direct access works flawlessly. Error persists for some weeks now and might not be solved by https://github.com/serlo/api.serlo.org/pull/314. But probably worth the wait to test again after deployment.
(ping @kulla)

**Comment by kulla** [comment]
It's an error in the source code. The exercise was injected with `>[Aufgabe](/54318 )` (with space in the end of the id) so that https://de.serlo.org/_next/data/BENofr8WfRd9yTMQCVWjV/de/54318%20.json instead of https://de.serlo.org/_next/data/BENofr8WfRd9yTMQCVWjV/de/54318.json (note difference of `%20` in the end) was requested. Source is fixed. @elbotho @Entkenntnis It might be good to trim the id of the injection before fetching to avoid similar bugs in the future (might also only occur in legacy documents since the new editor trims ids already...)

**Comment by elbotho** [comment]
Thank you!
