### ISSUE TITLE
Meta fields from API

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#95]
We need the following meta fields from the API to complete #94:
- description (for all uuids that support it)
- image (for og:meta tag, for all uuids that support it)

**Comment by inyono** [comment]
Meta Fields created by the author can now be queried via the API:
```graphql
{
  uuid(id:1855) {
    ...on Article {
      currentRevision {
        metaTitle
        metaDescription
      }
    }
  }
}
```

We still need to move the Normalizer / Adapter logic down to the frontend (which uses the meta fields and other revision fields to generate the actual meta data, and chooses an image by tag). Since this is specific to the web client used (and the meta tags desired), I'd rather let the frontend handle that themselves. Does this work for you?

**Comment by elbotho** [comment]
@inyono thats fine, could you maybe help me out with a link to the relevant file in serlo.org?
I get lost down there :)
I only found [this](https://github.com/serlo/serlo.org/blob/master/packages/public/server/src/module/Normalizer/src/Entity/Metadata.php) but that's about it.

**Comment by inyono** [comment]
- [Adapters](https://github.com/serlo/serlo.org/tree/master/packages/public/server/src/module/Normalizer/src/Adapter) contain the implementation for the specific types
- [NormalizeViewHelper](https://github.com/serlo/serlo.org/blob/master/packages/public/server/src/module/Normalizer/src/View/Helper/Normalize.php) contains the actual logic for adding meta tags

**Comment by Entkenntnis** [comment]
closing this in favour of #143
